# Numpy

# installing numpy modudles

In [2]:
!pip install numpy

In [5]:
import numpy as np

# Creating Numpy Array

In [10]:
list1 = [2,4,5]

In [14]:
array = np.array(list1)

<b> list1 is a 1D list representing rows and columns. np.array(list1) converts it into a 1D NumPy array for efficient matrix operations.</b>

In [16]:
	
print(type(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
1
(3,)


In [22]:
list2 = [
            [1,5,9],
            [6,8,2]
        ]

array2 = np.array(list2)

In [24]:
	
print(type(array2))
print(array2.ndim)
print(array2.shape)

<class 'numpy.ndarray'>
2
(2, 3)


<b> list2 is a 2D list representing rows and columns. np.array(list2) converts it into a 2D NumPy array for efficient matrix operations.</b>

<b> NumPy arrays can be created in several ways. Here are some of the most common methods:</b>

* array(): Creates NumPy arrays from Python lists
* zeros(): Creates NumPy arrays with all elements initialized to 0
* ones(): Creates NumPy arrays with all elements initialized to 1
* full(): Creates an array with all elements initialized to same user-specified value
* arange(): Creates NumPy arrays with a sequence of values (similar to python range() function)
* linspace(): Creates NumPy arrays with a sequence of evenly spaced values
* diag(): Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
* eye(): Creates NumPy array with ones on the diagonal and zeros elsewhere
* identity(): Creates an identity matrix
* random.rand(): Creates NumPy array of random numbers sampled from a uniform distribution

In [31]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# to get random numbers

In [37]:
import random

In [39]:
print(np.random.rand(2,3))

[[0.77457046 0.44070701 0.72818713]
 [0.79205787 0.86773523 0.0799793 ]]


In [42]:
list(range(5,55,5))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

# indexing and slicing

<b> NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.</b>

<b> Indexing:</b>

Indexing follows a simple rule that we may have encountered before. Let's give it a try.

* 1D Array: array_name[idx] (Similar to Python list)
* 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
* ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]
OR

* 2D Array: array_name[row_idx][col_idx]
* ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]

<b>Slicing:</b>

Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

* 1D Array: array_name[idx1:idx2:step]
* 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
* ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [48]:
a = np.array([1,5,3,7])

In [52]:
print (a[1])

5


In [54]:
print(a[1::2])

[5 7]


In [56]:
random_array1 = np.random.randint(low = 10, high = 50, size = (10,16,8))
print(random_array1.shape)

(10, 16, 8)


In [58]:
random_array1[4:5,:4]

array([[[26, 34, 46, 24, 49, 36, 12, 16],
        [37, 33, 29, 26, 30, 39, 30, 33],
        [16, 47, 33, 45, 30, 25, 26, 18],
        [11, 33, 21, 26, 17, 46, 46, 21]]])